apiVersion: v1
kind: Secret
metadata:
  name: breaddesk-secrets
  namespace: breaddesk
type: Opaque
stringData:
  DB_USERNAME: breaddesk
  DB_PASSWORD: breaddesk_password_change_in_prod
  JWT_SECRET: UFWNhBblvW5u3WcuSMv5lqT4CMOTopR62ryH+iHgiDRU+fT+I8GdcETPrsAQlD5y
